version: '3.8'
services:
  db:
    image: postgres:13
    container_name: is-a-word-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
